### ISSUE TITLE
testSubmit() fails

### ISSUE THREAD

**Issue by matadan** [phimage/Erik#25]
I cloned the repo and ran tests.

testSubmit() fails. I suspect this is related to #24 and will be fixed with #24.

Please let me know if there is anything I can do to help resolve these.

**Comment by phimage** [comment]
It seems to be not fixed

It could be a page loading end detection issue, or a parsing issue
 
edit: it seems to be a Kanna/libxml issue
I create an html file with google page content `<html>...</html>`, and after parsing some part are missing
maybe some weird javascript do this

**Comment by matadan** [comment]
I made a clean clone but after pod install the build fails with missing carthage files. So did carthage update to fix. I don't think tests compile properly with cocoapods only.

I have a hunch that it might be to do with css and the form being hidden and unhidden by css.

**Comment by phimage** [comment]
build system for this project is now carthage
carthage buid frameworks, and xcode use it
(I do not use cocoapods as main build system, because I could not find a way to make it compatible with carthage because cocoapods add many thinks into project target, maybe specific cloned targets...)

I must remove the Podfile!
only podspec must be here to allow cocoapod importation

--

For this test, maybe it's a Kanna issue or a libxml issue
I will investigate later

**Comment by matadan** [comment]
Google have changed their form id so the selctor won't pick iy

**Comment by matadan** [comment]
Google have changed their form ids so the test fails because it does not find the form.

To fix the test select the form like this:

`let form = doc.querySelectorAll("form").first as? Form`
